export const STATUTS_FORMATION = {
  EN_ETUDE: "En étude",
  VALIDEE: "Validée",
  REFUSEE: "Refusée",
  PLANIFIEE: "Planifiée",
  REALISEE: "Réalisée",
};

export const STATUTS_MOBILITE = {
  EN_ETUDE: "En étude",
  VALIDEE: "Acceptée",
  REFUSEE: "Refusée",
  PLANIFIEE: "Planifiée",
};

export const STATUTS_DEMANDE_FORMATION_LIST = [
  STATUTS_FORMATION.EN_ETUDE,
  STATUTS_FORMATION.VALIDEE,
  STATUTS_FORMATION.REFUSEE,
  STATUTS_FORMATION.PLANIFIEE,
  STATUTS_FORMATION.REALISEE,
];

export const STATUTS_DEMANDE_MOBILITE_LIST = [
  STATUTS_MOBILITE.EN_ETUDE,
  "Avis manager demandé",
  "En validation direction",
  STATUTS_MOBILITE.VALIDEE,
  STATUTS_MOBILITE.REFUSEE,
  STATUTS_MOBILITE.PLANIFIEE,
];

export const STATUTS_CYCLE_FORMATION = {
  PLANIFIEE: "Planifie",
  EN_COURS: "En cours",
  TERMINEE: "Termine",
  ANNULEE: "Annule",
};

export const STATUTS_CYCLE_FORMATION_LIST = [
  STATUTS_CYCLE_FORMATION.PLANIFIEE,
  STATUTS_CYCLE_FORMATION.EN_COURS,
  STATUTS_CYCLE_FORMATION.TERMINEE,
  STATUTS_CYCLE_FORMATION.ANNULEE,
];
